on:
  workflow_dispatch:
  
name: Quick tests of setup-r action

env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

jobs:
  testing:
    name: Test setup-r action
    runs-on: macos-13
    steps:
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
